kind: ConfigMap
apiVersion: v1
metadata:
  name: my-cm
data:
  #connection DB config
  database: "mysql"
  database_uri: "mysql://localhost:3306"

  #user interface
  font.title: "Arial Bold"
  background.color: "black"
  theme.1: "clean"
  theme.2: "dark"

---

kind: Pod
apiVersion: v1
metadata:
  name: pod-cm
spec:
  containers:
   - name: my-container
     image: nginx
     envFrom:
         - configMapRef:
              name: my-cm