apiVersion: batch/v1
kind: CronJob

metadata:
  name: my-cronjob
spec:
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
         containers:
          - name: job-container
            image: busybox
            command: [ "sh", "-c", "for i in 1 2; do echo Luck number $i = $((1+ RANDOM % 70)); done" ]
         restartPolicy: Never




