apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: front-end-ds
  labels:
    app: frontend

spec:
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      name: mypod
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
        - name: my-container-nginx
          image: tomcat

  selector:
    matchLabels:
      apps: my-app
