apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels: 
    app: frontend

spec:
  template:
    metadata:
      name: pod-nginx
      labels:
        env: production
    spec:
      containers:
        - name: nginx-cont
          image: nginx:1.14.2
  selector:
    matchLabels:
      env: production
  strategy:
    type: Recreate
  replicas: 5
