apiVersion: v1
kind: Endpoints
metadata:
  name: my-endpoint
subsets:
  - addresses:
     - ip: 77.68.88.76
    # - ip: 10.244.0.155
    # - ip: 10.244.0.154
    ports:
      - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-endpoint
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
