apiVersion: v1
kind: Service
metadata:
  name: my-endpoint
spec:
  ports:
    - name: http
      port: 80
---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-eps
  labels:
   kubernetes.io/service-name: my-endpoint
addressType: IPv4
endpoints:
  - addresses:
      - 10.244.0.3
ports:
  - name: http
    port: 80
    protocol: TCP
---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-eps-2
  labels:
    kubernetes.io/service-name: my-endpoint
addressType: IPv4
endpoints:
  - addresses:
      - 10.244.0.4
ports:
  - name: http
    port: 80
    protocol: TCP