apiVersion: v1
kind: Pod
metadata:
  name: frontend-srv
  labels:
    type: web-app
spec:
  containers:
    - name: apache-pod
      image: httpd
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-srv-nodeport
spec:
  type: NodePort
  selector:
    type: web-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30008





