apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
spec:
  containers:
    - name: apache-cont
      image: httpd
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
    - name: redis-cont
      image: redis
      resources:
        requests:
          cpu: "400m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"