apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: nginx-app-pods
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
spec:
  selector:
    matchLabels:
     app: nginx-app-pods
  serviceName: "my-svc"
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-app-pods
    spec:
      containers:
      - name: my-ctn
        image: nginx
