apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: nginx-app-pods
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
spec:
  selector:
    matchLabels:
     app: nginx-app-pods
  serviceName: "my-svc"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app-pods
    spec:
      containers:
      - name: my-ctn
        image: nginx:1.23.1
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: my-pv
  volumeClaimTemplates:
  - metadata:
      name: my-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi