apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: app.nginx
spec:
  containers:
    - name: my-nginx
      image: nginx
---

apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: app.nginx
  ports:
    - port: 80
      protocol: TCP
      name: http