apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - name: redis-cont
      image: redis
      volumeMounts:
        - mountPath: "/my-volume"
          name: "cache-volume"

  volumes:
    - name: cache-volume
      emptyDir: {}