apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
data:
  user: YWRtaW4=
  pass: bXktcGFzczEyMw==
stringData:
  my-db: mysql
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-vol-env
spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
        - secretRef:
            name: my-secrets
      volumeMounts:
        - mountPath: "/etc/my-vol"
          readOnly: true
          name: my-volume
  volumes:
    - name: my-volume
      secret:
        secretName: my-secrets