apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-vol-env
spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
        - secretRef:
            name: my-secrets
            optional: true
      volumeMounts:
        - mountPath: "/etc/my-vol"
          readOnly: true
          name: my-volume
  volumes:
    - name: my-volume
      secret:
        secretName: my-secrets
        optional: true